version: '3.8'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: TROCAR_O_NOME_AQUI
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db-mongo
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db-mongo:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./.docker/mongodata:/app/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
